export const CHARACTERS = [
  {
    id: 'sam',
    name: 'Sam',
    color: '#f0c674',
    rounds: 3,
    strategyId: 'allC',
    intro: "Sam. The friend who covered your rent that month you don't talk about. You've never paid him back and he's never asked.",
    summary: [
      "Sam always shared. Even when you didn't.",
      "He never asked you to stop.",
    ],
    revealName: 'Always Cooperate',
    revealNote: null,
  },
  {
    id: 'marcus',
    name: 'Marcus',
    color: '#a23b3b',
    rounds: 3,
    strategyId: 'allD',
    intro: "Marcus. Your old roommate. He still owes you for the last two months of utilities. He's been saying he'll pay you back since 2019.",
    summary: [
      "He always took. That was the play.",
      "Nothing you did was going to change the math.",
    ],
    revealName: 'Always Defect',
    revealNote: null,
  },
  {
    id: 'maya',
    name: 'Maya',
    color: '#5e8ca8',
    rounds: 8,
    strategyId: 'tft',
    intro: "Maya. Your business partner. Three years and she's never once taken more than her share.",
    summary: [
      "She was just matching you.",
      "Maya would have given you everything if you had. Whatever you chose, she chose back. The first move was always yours.",
    ],
    revealName: 'Tit-for-Tat',
    revealNote: null,
  },
  {
    id: 'theo',
    name: 'Theo',
    color: '#c87635',
    rounds: 5,
    strategyId: 'grim',
    intro: "Your cousin Theo. He hasn't spoken to your aunt since 2017. Nobody else in the family remembers what she did.",
    summary: [
      "Theo gave generously, right up until you took.",
      "After that, nothing you did mattered. There was no apology that would have worked. He had already closed the door.",
    ],
    revealName: 'Grim Trigger',
    revealNote: null,
  },
  {
    id: 'naomi',
    name: 'Naomi',
    color: '#a085bd',
    rounds: 5,
    strategyId: 'tf2t',
    intro: "Your sister Naomi. She's the patient one. She always has been.",
    summary: [
      "Naomi let things slide. Once. Twice, sometimes.",
      "She wasn't naive — she was watching the whole time. She just gave you room to be a person. Until you weren't.",
    ],
    revealName: 'Tit-for-Two-Tats',
    revealNote: null,
  },
  {
    id: 'ren',
    name: 'Ren',
    color: '#4c9c6a',
    rounds: 8,
    strategyId: 'pavlov',
    intro: "Ren. The friend who thinks in patterns. You've never quite been able to predict them.",
    summary: [
      "Ren wasn't watching you. They were watching what happened.",
      "Whatever worked, they kept. Whatever didn't, they dropped.",
    ],
    revealName: 'Win-Stay, Lose-Shift',
    revealNote: "Ren played something called Win-Stay, Lose-Shift. If a round went well for them — they got a high score — they did the same thing next time. If it went badly, they switched. Not watching you. Not punishing you. Just tracking outcomes and adjusting. It's adaptive, not reactive. And it's more successful than you might expect.",
  },
];
